default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: re_kiroku_app_development

test:
  <<: *default
  database: re_kiroku_app_test

production:
  <<: *default
  database: re_kiroku_app_production
  username: <%= ENV["RE_KIROKU_APP_DATABASE_USERNAME"] %>
  password: <%= ENV["RE_KIROKU_APP_DATABASE_PASSWORD"] %>
